# Generated by Django 2.0.8 on 2018-09-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('user_pass', models.CharField(max_length=20)),
                ('user_category', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pid', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_age', models.IntegerField(max_length=2)),
                ('p_gender', models.CharField(max_length=6)),
                ('p_address', models.CharField(max_length=100)),
                ('p_email', models.CharField(max_length=60)),
                ('flag', models.IntegerField(max_length=1)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
