# Generated by Django 2.0.8 on 2018-09-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('did', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=50)),
                ('d_specialization', models.CharField(max_length=50)),
                ('d_department', models.CharField(max_length=50)),
                ('d_slot', models.CharField(max_length=1000)),
                ('d_fee', models.IntegerField()),
                ('d_address', models.CharField(max_length=100)),
                ('d_email', models.CharField(max_length=60)),
                ('flag', models.IntegerField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='flag',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='p_age',
            field=models.IntegerField(),
        ),
    ]
